#!/bin/bash

set -eu

[ $# -eq 1 ] && [ "$1" == "--summary" ] && exit 2

if [ -t 0 ]; then
    exec >&2
    echo
    echo "Usage: clevis decrypt fido2 < JWE > PLAINTEXT"
    echo
    exit 2
fi

read -r -d . hdr64
if ! hdr="$(jose fmt --quote="$hdr64" --string --b64load --object --output=-)" ; then
    echo 'JWE header corrupt' >&2
    exit 1
fi
if [ "$(jose fmt --json="$hdr" --get clevis --get pin --unquote=-)" != 'fido2' ] ; then
    echo 'JWE pin mismatch!' >&2
    exit 1
fi
if ! hmac_salt="$(jose fmt --json="$hdr" --get clevis --get fido2 --get hmac_salt --unquote=-)" ; then
    echo "JWE missing 'hmac_salt' header parameter!" >&2
    exit 1
fi

if ! rp_id="$(jose fmt --json="$hdr" --get clevis --get fido2 --get rp_id --unquote=-)" ; then
    echo "JWE missing 'rp_id' header parameter!" >&2
    exit 1
fi
if ! cred_id="$(jose fmt --json="$hdr" --get clevis --get fido2 --get cred_id --unquote=-)" ; then
    echo "JWE missing 'cred_id' header parameter!" >&2
    exit 1
fi
if ! uv="$(jose fmt --json="$hdr" --get clevis --get fido2 --get uv --unquote=-)" ; then
    echo "JWE missing 'uv' header parameter!" >&2
    exit 1
fi
if ! up="$(jose fmt --json="$hdr" --get clevis --get fido2 --get up --unquote=-)" ; then
    echo "JWE missing 'up' header parameter!" >&2
    exit 1
fi
if ! pin="$(jose fmt --json="$hdr" --get clevis --get fido2 --get pin --unquote=-)" ; then
    echo "JWE missing 'pin' header parameter!" >&2
    exit 1
fi

fido2_tokens="$(fido2-token -L)"

if [ -z "${fido2_tokens}" ]; then
  echo "Please insert your FIDO2 token." >&2
  exit 1
fi

num_tokens="$(echo "${fido2_tokens}" | wc -l)"
if ((num_tokens > 1)); then
  echo "Warning: There are multiple tokens. Will use the first one." >&2
fi

fido2_token="$(echo "${fido2_tokens}" | head -n1 | cut -d':' -f1)"

client_hash="$(dd if=/dev/urandom bs=1 count=32 status=none | base64 -w0)"

f2a_uv="-t uv=${uv}"
if [ "${uv}" == "false" ] && ! fido2-token -I "${fido2_token}" | grep -qE "options:.* uv" ; then
  # Yubikey 5 NFC w/ libfido2 v1.14.0 does _not_ allow to explicitly specify "-t uv=true|false" below
  # (cf. https://github.com/Yubico/libfido2/issues/642#issuecomment-1303673367: "`uv` option [...] controls
  # device-native UV such as biometrics or on-authenticator PIN pad")
  f2a_uv=""
fi

hmac="$(printf '%s\n%s\n%s\n%s\n' "${client_hash}" "${rp_id}" "${cred_id}" "${hmac_salt}" | \
  fido2-assert -G -h ${f2a_uv} -t "up=${up}" -t "pin=${pin}" "${fido2_token}" | \
  head -n5 | tail -n1 | base64 -d | jose b64 enc -I -)"

# use the secret in a key wrapping key
jwk='{"alg":"A256GCM", "kty":"oct"}'
jwk="$(jose fmt -j "${jwk}" -q "${hmac}" -s k -Uo-)"

( printf '%s' "$jwk$hdr64." ; cat ) | exec jose jwe dec --key=- --input=-
